# Generated by Django 3.1.7 on 2021-03-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('company_description', models.TextField()),
                ('requirements', models.TextField()),
                ('location', models.CharField(blank=True, choices=[('onsite', 'On-site'), ('remote', 'Remote')], max_length=50, null=True)),
                ('salary', models.CharField(blank=True, choices=[('negociable', 'Negociable'), ('competitivo', 'Competitivo')], max_length=50, null=True)),
            ],
        ),
    ]
